ead:
  serviceRegistry:
    username: serviceregistry
    password: '{cypher}ewfwefwefwefwfefwefwefwefwefwefwefwefwefwefwefwefwef'
  auth:
    jwtSecret: '{cypher}t7w!z%C*F-JaNdRgUkXp2s5v8x/A?D(G+KbPeShVmYq3t6w9z$B&E)H@McQfTjWn'
    jwtExpirationMs: 14400000

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: ${APP_DOMAIN_NAME}
    non-secure-port: 80
